language: node_js
sudo: false
node_js:
- "6.16"
- "7.10"
- "8.15"
- "9.11"
- "10"
- "11"
before_install:
- ls
- openssl aes-256-cbc -K $encrypted_174cea7b8050_key -iv $encrypted_174cea7b8050_iv
  -in config/config.json.enc -out config/config.json -d
install:
- npm install
script:
- jest --coverage
- codecov
