language: node_js
sudo: false
node_js:
- 6.11.5
before_install:
- openssl aes-256-cbc -K $encrypted_174cea7b8050_key -iv $encrypted_174cea7b8050_iv
  -in config.json.enc -out config.json -d
install:
- npm install
script:
- jest --coverage
- codecov
